### ISSUE TITLE
ReClass Selecting Wrong Base Address

### ISSUE THREAD

**Issue by PwndDepot** [dude719/ReClassEx#29]
So basically there are a few modules that contain the same text. For example,
"client.dll" and "steamclient.dll" both contain "client.dll"
And for whatever reason, reclass will take the base address of "steamclient.dll" instead of "client.dll" (I even tried using quotes!)
Here's a pic of the bug:
http://image.prntscr.com/image/b908bb602e274e3cb4d68320d564c908.png

**Comment by Timboy67678** [comment]
was using StrStr to compare strings for text address, should be fixed now
https://github.com/dude719/ReClassEx/commit/fa2f119835aa86686b1c97f27949d38c773ca017

**Comment by dude719** [comment]
Thanks for opening an issue fr this :)
